AI Web Standards + Refactoring
hres/AngularApps pull request #264
Opened 2024-09-17 18:20 UTC by dmiraflorhc

2024-09-18 14:02 UTC, dmiraflorhc commented on projects/hpfb/sdk/css/rep.css
ART-3135. Added .css class selector that hides elements on the form that will only be visible to the screen reader. The list in the alert info text for priority review was not being announced by screen reader.

2024-09-18 14:03 UTC, dmiraflorhc commented on projects/hpfb/sdk/ui/expander/accordion/accordion.component.html
ART-3074. Added an aria attribute so that screen reader will read the expanded/collapsed state of accordion

2024-09-18 14:27 UTC, linghanHC commented on projects/md-ai/src/app/bio-material/material-list/material-list.component.ts
statusMessage probably should be bilingual, same comment for the device list

2024-09-18 14:30 UTC, linghanHC requested changes
see my comments for the mater-list

2024-09-19 19:09 UTC, dmiraflorhc commented on projects/md-ai/src/app/bio-material/material-list/material-list.component.ts
Not sure what you mean. The index starts from 0, so I had to add 1 to it. The id also gets incremented by 1 in the accordion

2024-09-19 20:12 UTC, linghanHC commented on projects/md-ai/src/app/bio-material/material-list/material-list.component.ts
is the "index" the index of elements in the list? 
let's say there are 3 records, record 2 is deleted, then make some changes to record 3, and then revert back record 3's content. Will (index + 1) find record3?

2024-09-20 12:15 UTC, dmiraflorhc commented on projects/md-ai/src/app/bio-material/material-list/material-list.component.ts
record3 will be Record 2 on the form and sr will announce "Record 2 changes have been discarded", but will still record3 on the output.

2024-10-04 14:44 UTC, merged