new pbv lib
hres/AngularApps pull request #317
Opened 2024-11-01 15:05 UTC by DDoucetHC

2024-11-01 19:03 UTC, linghanHC requested changes

2024-11-01 19:03 UTC, linghanHC commented on projects/hpfb/sdk/ui/information/privacy-statement/privacy-statement.component.html
where purposeOfCollection is used for the 3 pvb apps?  Remove it if not used in the 3 pvb apps.

2024-11-01 19:03 UTC, linghanHC commented on tsconfig.json
The path is required if you use the pbv lib directly from the project folder/dist folder. It is not required if you use the packaged tgz pvb lib.  Remove it if the intention is to use the packaged versioned pvb lib.

2024-11-01 19:03 UTC, linghanHC commented on projects/hpfb/pbv/package.json
1. version it 1.0.0
2. add  "buildNumber": 0 (ref https://github.com/hres/AngularApps/blob/main-mono-repo/projects/hpfb/sdk/package.json). re-run the "pbv-lib:buildPackageAndMove" script then buildNumber will be incremented automatically

2024-11-04 14:09 UTC, DDoucetHC commented on projects/hpfb/sdk/ui/information/privacy-statement/privacy-statement.component.html
i thought I wasnt supposed to delete anything from sdk?

2024-11-04 14:28 UTC, linghanHC commented on projects/hpfb/sdk/ui/information/privacy-statement/privacy-statement.component.html
My mistake. This comment is for "projects/hpfb/pbv/src/privacy-statement/privacy-statement.component.ts"

2024-11-04 14:28 UTC, linghanHC commented on projects/hpfb/pbv/src/privacy-statement/privacy-statement.component.ts
where purposeOfCollection is used for the 3 pvb apps? Remove it if not used in the 3 pvb apps.

2024-11-04 14:58 UTC, DDoucetHC commented on projects/hpfb/pbv/src/privacy-statement/privacy-statement.component.ts
purpose of collection is used in the privacy notice statement for all the pbv forms and its a different text then the sdk ones if that's what you mean

2024-11-04 18:29 UTC, linghanHC commented on projects/hpfb/pbv/src/privacy-statement/privacy-statement.component.ts
I'm saying do you use @Input() purposeOfCollection?; for pvb apps? if not, delete it

2024-11-04 18:33 UTC, linghanHC commented on apps/pbv-rt/src/app/container/container.component.html
[purposeOfCollection]="'purpose.of.collection' | translate"  
is it needed for pvb rt app?

2024-11-04 18:49 UTC, DDoucetHC commented on apps/pbv-rt/src/app/container/container.component.html
i believe it depends if we wanna keep the if else statement from before that sdk was using and the default template

2024-11-04 19:43 UTC, linghanHC commented on apps/pbv-rt/src/app/container/container.component.html
if you are repeating the privacy statement from sdk, then why do we need a new one in pvb lib?
@AMckayHC what do you think?

2024-11-04 19:45 UTC, DDoucetHC commented on apps/pbv-rt/src/app/container/container.component.html
its a different inside text which i guess we can use the same privacy statement and change the text in the json file

2024-11-06 12:49 UTC, AMckayHC commented on apps/pbv-rt/src/app/container/container.component.html
Usually we do change the text in JSON if we can, maybe you and I can chat/review again?

2024-11-06 13:19 UTC, linghanHC commented on projects/hpfb/sdk/ui/information/privacy-statement/privacy-statement.component.html
don't think the change is correct? have you tested?

2024-11-06 15:05 UTC, DDoucetHC commented on projects/hpfb/sdk/ui/information/privacy-statement/privacy-statement.component.html
i dont think ive tested with a json variable but it shows the template now which didnt before. ill test with json

2024-11-06 15:08 UTC, linghanHC commented on projects/hpfb/sdk/ui/information/privacy-statement/privacy-statement.component.html
test with MF too

2024-11-06 16:28 UTC, DDoucetHC commented on projects/hpfb/sdk/ui/information/privacy-statement/privacy-statement.component.html
when i add a purpose.of.collection in the json it overrides the default and if nothing in json it used the default. I tested in mf-rt and pbv-rt

2024-11-06 20:24 UTC, linghanHC approved these changes

2024-11-07 11:41 UTC, AMckayHC approved these changes

2024-11-07 11:49 UTC, merged