Jira 347 csp new drug submission information
hres/AngularApps pull request #337
Opened 2024-11-15 15:27 UTC by tfang54321

2024-11-15 15:40 UTC, AMckayHC requested changes
Can you update the French JSON file? You can find the french text here: https://health-products.canada.ca/forms/certificate2023/formulaire-certificat-protection-supplementaire-2023.html

2024-11-20 19:08 UTC, tfang54321 commented
@AMckayHC  I have translate some csp label to french. and create new build script for csp. please review, approve and merge if everything looks good.  thanks

2024-11-21 11:57 UTC, AMckayHC commented on apps/csp/build-content-configs/metaData-en.html
Need to change metadata to be what is in CSP Production.

2024-11-21 11:57 UTC, AMckayHC commented on apps/csp/build-content-configs/metaData-fr.html
Need to change metadata to be what is in CSP Production.

2024-11-21 11:59 UTC, AMckayHC reviewed
Can you change breadcrumbs to be copied over from CSP, thanks!

2024-11-21 15:08 UTC, tfang54321 commented on apps/csp/build-content-configs/metaData-fr.html
changes made. please review.

2024-11-21 15:58 UTC, AMckayHC approved these changes

2024-11-21 18:59 UTC, merged